### PR TITLE
Adding getRandomTile and making tile variables into arrays

### LINKED ISSUE #96: Adding the Ability to Select Multiple Tiles
Basically what is said on the title. Figuring out a way to be able to add in multiple tiles into the script so that it can pick between the tiles made randomly.

### PR DESCRIPTION
**Pull request by fergut3**
# PR Template

## Headings That Should Be Included
- [ ] **Description**

This PR is meant to allow the ability to add in multiple tiles into mapgenDLA and edgeTiles script so that the map generates random tiles
image

- [ ] **Methods Implemented**

Mostly, just added a function called getRandomTile(GameObject[]) that will return a random index of a game object array in both mapgenDLA and edgeTIles

- [ ] **Fields Implmented**

Changed the GameObject variables into arrays that can be added into from the unity editor. In addition a non-array starting tile was made so maps could start with a static tile.

image

- [ ] **Changes to Unity Editor (Screenshots, if applicable)**

image

Areas affected in the editor are highlighted.

- [ ] **Related Issue**

Related to issue #96 

- [ ] **Mention Reviewers**

@cozloff @tnishamon

### CODE REVIEW

**Review by cozloff — APPROVED** [review]
This PR is definitely a great enhancement to the mapgenDLA and edgeTiles scripts because it is implementing the ability to incorporate multiple tile types dynamically in map generation. The getRandomTile(GameObject[]) function is a creative way to randomly selects tiles from an array, creates varied and interesting map designs. I like the extension of GameObject variables to arrays for more versatile map initialization, with the thoughtful inclusion of a non-array starting tile for consistent starting points. This update all together appears well-constructed and likely to significantly enhance the map generation capabilities, potentially improving both the visual diversity and gameplay experience.

**Review by tnishamon — APPROVED** [review]
This is a nice easy way to implement random tiles for now. Thank you Tristan. Once we are done designing the levels with their backgrounds and tiles, we should look into using AssetBundles, since this will let use just load prefabs directly from the Bundles rather than pulling everything into serialized fields (so we have less of a hassle in the editor and it helps our Unit Tests). 

This is an enhancement we can worry about later once we push past our Mean Viable Product. I think this is good to merge in once the conflicts are fixed.

**Comment by tnishamon** [comment]
Screenshot 2024-04-12 at 4 02 48 PM
Screenshot 2024-04-12 at 4 03 15 PM

Looks good to me for merging

**Comment by SwiftNemesis** [comment]
Since we have two reviews already, I'll allow either @cozloff or @tnishamon to merge it. Just sending a ping to update the thread.

**Pull request merged**
