### PR TITLE
Boss Levels (1st Boss: City, 2nd Boss: Forest, 3rd Boss: Void)

### PR DESCRIPTION
**Pull request by Intensifiesx**
- [x] **Description**

This PR is about the raid boss encounter for the first level. It will add a new scene, boss, and some new dynamic mechanics to the scene.

- [x] **Methods Implemented**

N/A

- [x] **Fields Implmented**

N/A

- [x] **Changes to Unity Editor (Screenshots, if applicable)**

WORK IN PROGRESS..
image

- [x] **Related Issue**

N/A

- [x] **Mention Reviewers**

N/A

- [x] **Miscellaneous & Images**

N/A

### CODE REVIEW

**Comment by Intensifiesx** [comment]
image

**Comment by Intensifiesx** [comment]
# Level 1

image

# Level 2 [WIP]

image
image

**Comment by Intensifiesx** [comment]
# Level 3 Arena

**Comment by Intensifiesx** [comment]
All levels have been finished. If you would like, adding touchups and such would be appreciated. One issue is that on level 2, level colliders do not work. Hope someone could fix that. Thank you

# Level 1 (Inferno's Embrace)
image

# Level 2 (Forest of the Lost)
image

# Level 3 (Forgotten Purgatorial Abyss)
image

**Comment by SwiftNemesis** [comment]
Please reopen this when it's ready to be submitted. Draft will still be updated.

**Review by SwiftNemesis — APPROVED** [review]

**Comment by fergut3** [comment]
I made a tiny adjustment to make sure the boss level 1 matches colourwise with city level. I'll go ahead and merge it right now.

**Comment by AlphabetWolf** [comment]
Those levels looks very nice, and I did some audios for each boss as well.

**Comment by Haikp** [comment]
Forgot to mention, this PR added tunability to all mobs including the player via variables in the Unity inspector, allowing for people to playtest. Everyone does not need to understand the code, acting like a black box and letting people still give their opinions without needing someone from the gameplay department to be with them to guide them through the code.

**Pull request merged**
