### PR TITLE
 Implementation of Bomber Droid Mob 

### PR DESCRIPTION
**Pull request by YordyCruz**
# Pull Request - Completed Bomber Droid Mob

## Bomber Droid
- [ ] Summary
Implemented the the Bomber Droid with its  state machine handling the behaviors idling, following the player (aggro), attacking, taking damage, and death.

- [ ] **Methods Implemented** (Changes mostly in Bomber FSM folder)
- BomberDroid State Manager
-  aggroState 
- attackState 

- [ ] **Features Implemented**
- Attacks only when the droid is above the player 
- Causes a small knockback when the player is attacked
- [ ] All of animations 
- Death
- Hit
- Idle
- Move
- Attack 

- [ ] **Related Issue**
- 

- [ ] **Changes to Unity Editor (Screenshots, if applicable)**
image

- [ ] **Mention Reviewers**
@Haikp  @koyomi7 @voxelit 

- [ ] **Miscellaneous & Images**
Bomber Droid Attacking 
BomberAttacking

Bomber Droid Dying
  BomberDying

Future implementation: Adding a sound to alert the player of the attack or when the drone flying by would be nice.

### CODE REVIEW

**Comment by Haikp** [comment]
There are some concerning issues that can be pointed out, being the elevation of this mob. This mob I'm assuming is meant to be something thats in the air. as our game is kind of 2D, we need to create illusion of it being in the air. Perhaps add a drop shadow to the character where its base is? This leads to another problem though of how its mean to hit by our main character. Melee attacks shouldn't work, so we could have it so that you can only use ranged attacks, although I'm not to sure as to how "fun" that would be if our character had to deal with 20 of these mobs. We do have more assets regarding magic spells that our character could cast to attack these fight these mobs that we could look into. The bottom line is, this mob is a flying creature, and there should probably be something for that. It does seem kind of out of place to have one flying mob in the entire game, but it'll probably be alright. If you have any other suggestions revolving around this, then lets talk about it before you fully implement the bomb drone. This should probably be addressed a bit more as it involves adding mechanics to our main character. Good job on the base implementation of the bomb drone though.

**Comment by koyomi7** [comment]
First off good job on the mob. As Kelvin said it causes a small issue about the 2D aspect of the game. I think as long as we make it very low HP so players can one shot range attack him, and make another shape to mimic the shadow we are good

**Comment by YordyCruz** [comment]
Thanks for the feedback! 
The mob is only hit from player range attacks and has shadow now.
BomberUpdated

**Comment by Intensifiesx** [comment]
Nice progress on the mob. Seems very fluid. I've tried it out and i think its a pretty cool idea for an air attacker. It really is coming along! :D

**Comment by koyomi7** [comment]
Very good update, that fixes accordingly everything we've mentioned. Thanks for your hard work

**Pull request merged**
