### PR TITLE
Implement Biased Pathfinding in MapGen for Directed Map Layout

### LINKED ISSUE #34: Biased Path Finding Algorithm
The mapgen DLA algorithm needs to implement some sort of biased path finding algorithm to generate tiles to shape the map towards a certain direction. This will ensure that the map and its exit can be altered to our specifications, and more playable by our judges.

### PR DESCRIPTION
**Pull request by cozloff**
# Description
In this update,  a significant enhancement to the map generation algorithm used in our project. I've implemented a biased pathfinding mechanism that guides the map generation towards a specific direction towards an endpoint, ensuring that the map layout is more predictable and tailored to our design goals for the judges.

## Changes in MapGenDLA
1. Biased Pathfinding Algorithm: The core of this update is the introduction of a biased pathfinding mechanism that guides the tile generation process towards a predetermined endpoint, while still allowing for randomness and branching to maintain a natural and exploratory feel to the map.

2. Endpoint Generation: The `GenerateRandomBorderEndpoint` function has been enhanced to select a random point along the border of the map, serving as a target for the biased pathfinding. This ensures the map has a directionality, leading players towards a goal while exploring.

3. Tile Generation Bias: Within the `UpdatePosition` function, we introduced a bias towards the endpoint. The algorithm now includes a chance-based decision to either move directly towards the endpoint or continue with a random walk, providing a balance between directed exploration and open-ended map layout.

4. Closest Tile to Endpoint for Exit Placement: To ensure the exit is placed in a reachable and logical position, the `FindClosestGeneratedTileToEndpoint` function has been implemented. It identifies the generated tile closest to the predetermined endpoint, ensuring the exit is accessible to players.

5. Exit Placement Refinement: The `AddExit` function has been refined to place the exit on the closest tile to the endpoint. This adjustment ensures that the exit is always placed on an actual tile within the game world, enhancing the consistency and integrity of the map's layout.

Conclusion
This update to the map generation algorithm marks a significant step forward in our game's development, introducing a more complex and engaging mechanic that enhances the player's experience. The implementation of biased pathfinding, combined with strategic exit placement, creates a more player friendly game environment.

Closes: #34

### CODE REVIEW

**Comment by cozloff** [comment]
commit-biased-algo

**Comment by cozloff** [comment]
You can also modify the bias percentage to make it more random again.

**Comment by tnishamon** [comment]
Great job with this implementation. I like the direction to work with biases, I think it makes the procedural generation feel a bit more varied. 

I will mess around with it tomorrow and see what it can do.

**Comment by SwiftNemesis** [comment]
This looks awesome, thank you for the contribution! I love the separation and the change there to make it more random based on the endpoint tiles. Definitely makes it feel more procedurally generated for an exit as well.

All the other changes are great as well!

**Comment by fergut3** [comment]
Good method to add bias into the tile generation. I do see the bias generation is random at the moment, which is pretty nice. If we wanted to make the map bias in different ways on each floor i could see it working easily by altering the code, but that's just me throwing an idea in the air.
Good idea with snapping the exit into the nearest exit it'll definitely make it look cleaner.

**Comment by SwiftNemesis** [comment]
I'll go ahead and close this PR since most of the team is in agreeance.

**Comment by Haikp** [comment]
Well done implementing what we discussed before. Implementing a bias for the map gen is important when it comes to our game in particular. As though it is isometric, I believe that there should be a horizontal bias for the sake of our assets being meant for 2D. Combat animations thus are intended to be attacking only left to right. Horizontal map gen bias helps with the potential vertical weakness our game currently has. Good job!

**Pull request merged**
