### PR TITLE
Finished Dagger Mushroom mob

### PR DESCRIPTION
**Pull request by voxelit**
Finished Dagger Mushroom mob

# PR Template

## Headings That Should Be Included
- [ ] **Description**

The Dagger Mushroom is a simple mob that dashes forwards and attacks. This pull request includes the mob behavior, animation, and attacks.

- [ ] **Methods Implemented**

Please list your methods that you have implemented in your PR. This will make it easier for the reviewer to keep track of what changes you've made.

- [ ] **Fields Implmented**

DaggerMushroomStateManager
DaggerMushroomAnimatorController

- [ ] **Changes to Unity Editor (Screenshots, if applicable)**

image

- [ ] **Mention Reviewers**

@Haikp @koyomi7 @YordyCruz 

- [ ] **Miscellaneous & Images**

I accidentally committed my work while I was trying to resolve conflicts on my local fork. 
Also, I would like to implement the throwing attack in the future if there is time.

### CODE REVIEW

**Comment by koyomi7** [comment]
Good job on this mob. It is a pretty straightforward mob for players to fight against at an easy level, i don't think there will be any big issue about it. Thanks for your hard work.

**Comment by YordyCruz** [comment]
The Dagger Mushroom mob is well designed! 

I was testing the latest uploaded version, I've noticed that the player isn't taking damage during the attack animation due to the current attack range.  I suggest increasing the Dagger Mushroom's attack range from 2 to 3 to ensure the animation causes damage. 

Additionally, the attached image reveals that the mob is using a box collider for its attack, which allows the player to damage it from an long range. It would be better to replace this with a Capsule Collider 2D to address the issue.

Thank you for all the hard work you do!

image

**Comment by voxelit** [comment]
Thank you Mr. Yordy for your input! I have added your suggestions into your latest commit and your advice has really improved the mob a lot. I appreciate your help!

I have also added damage immunity during its attacks, which visually makes sense since its animation implies that it is moving too fast to be hit. If this addition feels unnecessary or poorly implemented, please let me know.

**Comment by Haikp** [comment]
Great job on the changes, and well done on implementing the Dagger Mushroom, looks good to me.

**Pull request merged**
