### PR TITLE
Installation of Code Coverage Dependencies

### PR DESCRIPTION
**Pull request by tnishamon**
Walked through step-by-step the way to install and setup testing and code coverage for Unity. Further explanation will be shown in the pull request. This is related to specifications in Issue #30

### CODE REVIEW

**Comment by tnishamon** [comment]
Below will be a step-by-step installation and set up of Code Coverage and Implementing tests in Unity. This is to ensure that any dangling branches are able to maintain and setup their tests. 

Step 1: Install Code Coverage Package (duh)


Step 2: Open up the Code Coverage in Window > Analysis > Code Coverage



Step 3: Create a new Assembly Definition. This will be essential when generating and running your tests. We can tune the parameters as the game becomes more modular and we add new features, but just a basic assembly should work for now. 



Step 4: Create a new PlayMode Test Assemblies folder. This should mode likely be under 2DRove > Assets and will make a new Tests folder and the assemblies for the tests in the folder. 



Step 5: In the assembly file in Step 3, open it in the inspector and add the Tests assembly in the Assembly Definition References. Additionally, under the Code Coverage tab, also add the Tests assembly to Included Assemblies. 



Step 6: Make sure you are in the Tests folder in the editor and create a new test. Rename it to whatever you would like to call your test. The second picture should show you what a basic test script looks like. 



Step 7: Start writing tests and run them. Under Test Runner (should open up when you open Code Coverage in Step 2), you should be able to run tests that you have created. Once you run a test and there is no compilation error, you should get a window opened to see your generated Code Coverage HTML report. These will always be stored in your Code Coverage folder which should be stored in the project files now.

**Comment by tnishamon** [comment]
image
We have the pipeline set up, I just need to figure out stuff for GitHub secrets because that seems to be throwing an error (even tho I'm pretty sure I set up the secrets correctly).

**Comment by tnishamon** [comment]
image
I have figured out secrets issues and it authenticates. The testing environment still fails, but I am closer to getting it to work.

**Comment by tnishamon** [comment]
Quick walk through of my fix: 
image
I created these variables to pull from our secrets in settings

This is where I placed secrets: 
image

I think they pull from repo secrets, but I created env secrets too since I'm pretty sure that's where workflow is supposed to pull from. I used my Unity Serial Key and login for the secrets: 
image

**Comment by tnishamon** [comment]
image
I got tests to run and pass! I think all I need to do is get the workflows to get read and write permissions. 

I should have listed what fixed this:
image
This change in the YAML file was needed so it knows the path and gets a GitHub token which I think it also needs to authenticate.

**Comment by tnishamon** [comment]
I did it. We now have a framework for automatic testing and coverage: 
image

**Comment by tnishamon** [comment]
image
I added functionality to download the HTML coverage report. I don't know how to show this in GitHub actions for now (I'll figure it out). 

image

I think with this, this is ready to be merged in main, but needs review.

**Comment by tnishamon** [comment]
image
I added the following lines to .gitignore
I foresee mergeconflicts being the bane of our existence, so this hopefully helps a tiny bit

**Review by cozloff — APPROVED** [review]
Achieving 100% line and method coverage is commendable. It suggests that the tests are comprehensive and all executable code has been exercised by the tests. The tests are well-structured between standard test cases and Unity-specific coroutine tests, demonstrating a good understanding of the Unity testing framework. The test code is clean and free from unnecessary clutter, which makes it easy to read and understand.

**Comment by SwiftNemesis** [comment]
As I've commented in previous PRs, this looks awesome and thank you for the contribution.

This'll be integral to the testing and further progress of our project.

Going ahead and approving this as well like I did with the mapgentesting PR.

**Review by SwiftNemesis — APPROVED** [review]

**Pull request merged**
