### PR TITLE
Underworld Tiles

### PR DESCRIPTION
**Pull request by tnishamon**
# Underworld Tiles

- [x] **Description**

This PR will add the prefabs for the Underworld/Purgatory level (Level 3). 

- [x] **Methods Implemented**

Screenshot 2024-04-13 at 5 21 06 PM
Added method to generate a background.

- [x] **Fields Implmented**

N/A

- [x] **Changes to Unity Editor (Screenshots, if applicable)**
Created the following prefabs:
Un
Screenshot 2024-04-13 at 5 22 06 PM

UnBorder
Screenshot 2024-04-13 at 5 22 47 PM

And UnEdges
Screenshot 2024-04-13 at 5 23 21 PM
Screenshot 2024-04-13 at 5 23 25 PM
Screenshot 2024-04-13 at 5 23 33 PM
Screenshot 2024-04-13 at 5 23 43 PM
Screenshot 2024-04-13 at 5 23 49 PM
Screenshot 2024-04-13 at 5 23 56 PM
Screenshot 2024-04-13 at 5 24 04 PM

- [x] **Related Issue**

Resolves Issue #92 

- [x] **Mention Reviewers**

@Haikp @SwiftNemesis @cozloff @fergut3 @Intensifiesx 

- [x] **Miscellaneous & Images**

Please add anything else you would like to be noted.

### CODE REVIEW

**Comment by tnishamon** [comment]
This is what I have so far for my implementation for the tiles for the level. Give me some feedback on what I have so fair, and I'll keep working on making more tiles to vary up the level. 
SC: of how it looks without main tiles being finished

**Comment by tnishamon** [comment]
This is what I have so far for my implementation for the tiles for the level. Give me some feedback on what I have so fair, and I'll keep working on making more tiles to vary up the level. 
SC of how it looks without main tiles being finished: 
Screenshot 2024-04-13 at 5 27 13 PM

**Comment by Haikp** [comment]
Something that I suggest is having more tile variety. From the POV of the player, its pretty jarring to see the same time just span across the whole map. I'm not saying that you should remake the tiles completely, but there things you can add to give more variety, as there are different versions of the tiles the lava tiles and ash blocks(?).

**Comment by tnishamon** [comment]
image
Working on mixing up the Background tiles

**Comment by tnishamon** [comment]
image
Here is what the most recent variation of the map looks like. There's still some enhancements to be made, but the basic tiles we need for the theme are all there with variation

**Comment by tnishamon** [comment]
image
thingy

**Comment by SwiftNemesis** [comment]
From a visual aspect, I like it so far but it can definitely be a bit jarring on the eyes depending on the coloring. This is however subjective and it does fit a general underworld/almost like mario lava land (world 8 typically) type style.

Something else to note, I cannot test the scene floor in my Unity when I checkout to the PR branch. Can you please create a copy of the scene and name it something else besides Floor 3? It seems to be a duplication error which I'm getting in my unity editor.

Whenever I load up Floor 3, it's just empty with nothing in it.

**Comment by SwiftNemesis** [comment]
image

I think the texture change between tiles can be a little jarring but I'm trying to think of ways to solve that. Overall it looks great though and I really like the lava coloring. It was hard to see from screenshots but after testing, i think the color is pretty spot on and you get the basalt theme really done well.

**Comment by tnishamon** [comment]
@SwiftNemesis Maybe to fix the flow of tiles we try and put different colored tiles on different places on the Z-axis and on a different sorting layer. This means we don't have to mess much with the algorithm it'll look a little better. I might be able to just mess with the way the tiles look so they all look good together. I did that for the background tiles it just took a while.

**Pull request merged**
