### PR TITLE
Applies Augments to Player

### PR DESCRIPTION
**Pull request by voxelit**
# PR Template

## Headings That Should Be Included
- [ ] **Description**

This pull request applies the augment system created to the Player. When selecting an augment, the method associated with that augment should change the required fields in the Player to enable that specific augment.

- [ ] **Methods Implemented**

In PlayerController.cs:
IncreaseSpeed
IncreaseMana
IncreaseHealthRegen
regenHealth
IncreaseDamage
IncreaseCrit
EnableBurning
IncreaseBurn

In NewEnemy.cs:
EnableBurning
setBurnDamage
burn

- [ ] **Fields Implemented**

In PlayerController.cs:
speedBoost
maxMana
mana
rangeMana
healthRegen
lastRegen
regenCooldown
damageBoost
critRate
burning
burnDamage

in NewEnemy.cs:
isBurning
lastBurn
burnCoolDown
burnDamage

- [ ] **Changes to Unity Editor (Screenshots, if applicable)**

image

image

- [ ] **Mention Reviewers**

@Haikp @koyomi7 @YordyCruz @SwiftNemesis @Intensifiesx 

- [ ] **Miscellaneous & Images**

In order to incorporate Offensive augments, the damage calculation formula has been modified. The base damage for slash attacks are now set to 3, while the dash attack is set to 5.

```
float totalDamage =  playerAttackDamage * damageBoost; // increase total damage by damageBoost
                float crit = Random.Range(1, 100);
                if(crit <= (critRate * 100))
                {
                    totalDamage *= 1.5f;  // use random number to determine if player hits a crit or not
                }
                enemyScript.TakeDamage(totalDamage);
                if(burning) {
                    //applies burning to enemies
                    enemyScript.EnableBurning();
                    enemyScript.setBurnDamage(burnDamage);
                }
```

In addition, the ranged attack has been modified to cost mana. Initially, the player's mana is set to 50 and each ranged attack will cost 5 mana. If the cost of the spell is greater than the current mana, the spell cannot be cast.

### CODE REVIEW

**Comment by koyomi7** [comment]
The augment system is progressing faster than expected. Thank you for your hard work Ms. Kaitlyn. Is the enemy damage-dealing problem fixed?

**Comment by voxelit** [comment]
> The augment system is progressing faster than expected. Thank you for your hard work Ms. Kaitlyn. Is the enemy damage-dealing problem fixed?

Yes, the enemy damage-dealing problem has been fixed. Please ensure that the Player is set to the Player level when testing.

**Comment by SwiftNemesis** [comment]
Alrighty, so I went ahead and create a test example of the code you requested @voxelit. Please look in `AugmentObject.cs`and work in there to attach the backend methods to the frontend. I also made it so that it grabs the current player object in the scene and adds the augment to it. I left some comments and notes on how to do it but feel free to message me on discord if u need more help.

I cleaned up the structure as well to make sure everything actually works properly for when a method is invoked and I was able to get it working with the test case I gave.

**Review by SwiftNemesis — APPROVED** [review]
Great work on this. I will go ahead and create a separate PR (either from me or you) connecting it all together with the augment frontend. Continue working on the other augments like we discussed within playercontroller and I can keep connecting it to frontend!

**Pull request merged**
