### PR TITLE
Initial Augment Implementation

### PR DESCRIPTION
**Pull request by SwiftNemesis**
# Description

Within this PR I have created the initial augment system which includes two files called `Augments.cs` and `SelectedAugmentList.cs`. I'll go into further detail with each file in the following headings. 

This implements the UI elements needed to make an augment system similarily inspired by TFT where we can create a set of augments that can be randomly chosen from and then will be applied the character.

In its current implementation, most things are currently placeholder and it's mostly to make sure the UI front end parts of it actually function properly. As for the backend, i will be working on that in a following PR later on.

# Methods Implemented

### `void Start()`

This function is basically like a constructor and should be self explanatory. Implements augment list and adds listeners for associated buttons in the unity editor.

###  `void showAugmentOverlay()`

This pauses the game and shows the augment overlay. This function can be implemented to appear upon a boss kill or some other form of boolean interaction.

### `void closeAugmentOverlay()`

Same goes here. I added a close button. This closes the menu and unpauses the game.

### `void addAugment(Button button)`

This will actually add an augment to the list of augments the player acquires.

### `void pause()`

Pauses the game

### `void Reroll()`

Reroll as a function takes and randomizes 3 possible augments that will appear for the player. These will not include augments the player has already obtained. It also creates all the connections for the buttons and passes the button to `addAugment`

### `void Start()`

Like the previous function, it's a constructor and this one only adds to button calls.

### `ShowAugmentList()`

Pauses the game.

This shows the augment list. This is done using a prefab and a list transform (vertical in this case) that will print the prefab with the name of the augment. I plan to implement this later to be a clickable button where you can read the description fully of the augment in a nice contextual menu.

### `void CloseAugmentList()`

Unpauses the game.

Stops showing the overlay.

# Fields Implemented

## Augments.cs
```c#
    public Button[] augmentCards;
    public Button rerollButton;
    public Button augmentDebugButton;
    public Button augmentOverlayCloseButton;
    public Canvas augmentOverlayCanvas;
    public static List<string> chosenAugments;
    private List<string> allAugments;
    private List<string> currentChoiceAugments;
```

## SelectedAugmentList.cs
```c#
    public Button closeAugmentList;
    public Button augmentList;
    public Canvas augmentListOverlay;
    public GameObject augmentPrefab;
    public Transform augmentListTransform;
```

# Demo in Unity

AugmentSystemDemo

# Related Issue

Related to issue #74. This issue should be a continuous thread and have multiple PRs attached due to the nature of the system being quite dense.

# Mention Reviewers

Please review: @Haikp & @koyomi7 

# Misc & Images

Let me know if there's any changes you'd like to see. Everything is subject to change in terms of UI design to fit the overall theme of the game.

### CODE REVIEW

**Comment by Haikp** [comment]
Very nice job on the augment system. Everything else shouldn't be so difficult to implement. We do need to find fitting visuals, which i think we could probably make something out of the UI prefab that bought previously. A bigger concern is probably more of the creative aspect, trying to figure out potential augments we could have. An idea I'd like to use of TFT once again was the use of silver, gold, and prismatic augments, and we could just reuse some ideas. For instance, Cybernetic Bulk has 3 different versions, and we could do the same thing to buff our characters' stats. That would help with increasing the augment density for more varied gameplay. There are also more prefabs that we have yet to use in the bundle that we bought, so we could use abilities or something as on the augments. There is a ranged attack, so we would be replace the ranged attack slot with a different ranged attack. More brainstorming will be done next meeting, good job.

**Review by Haikp — APPROVED** [review]
Good job on the front end of augments.

**Review by koyomi7 — APPROVED** [review]
nicely done

**Review by cozloff — APPROVED** [review]
This PR is great groundwork for an augment system, the focus on UI elements for selecting and applying augments to characters, is important for making an engaging game. These are foundational methods for initializing the system, displaying and managing the augment selection overlay, and handling player interactions like augment addition and rerolling.  The inclusion of UI elements and fields is well thought out, underscoring the importance of a seamless player experience. Future enhancements could benefit from detailed code documentation and perhaps robust error handling.

**Pull request merged**
