### PR TITLE
Fully implement mapgen into main

### PR DESCRIPTION
**Pull request by tnishamon**
# Full implement mapgen into main

## Teehee
- [ ] **Description**

This PR is just to merge the other two pull requests from @fergut3 and @cozloff into main (which recently merged with main).

- [x] **Methods Implemented**

N/A refer to Pull Request #62 and #50 

- [x] **Fields Implmented**

N/A refer to above

- [x] **Changes to Unity Editor (Screenshots, if applicable)**

N/A refer to above

- [ ] **Related Issue**

PR #62 related to Issue #61 

- [x] **Mention Reviewers**

N/A

- [x] **Miscellaneous & Images**

N/A

### CODE REVIEW

**Comment by tnishamon** [comment]
Some additional testing  showed that our border creation broke once we started applying edge borders (since they would switch). What we probably need to do is make sure all tiles are in one dictionary and have the border generation happen later in the mapgen pipeline, but for now I fixed the issue by changing a few lines in CreateBorder.
Screenshot 2024-04-06 at 11 56 37 AM


Screenshot 2024-04-06 at 11 53 08 AM

Lines changed: 
Screenshot 2024-04-06 at 11 59 13 AM

**Comment by Intensifiesx** [comment]
The edge tiles are pretty cool but since there are no collisions for it then player will go out of bounds. I will be adding collisions to this:
image
image

Overall nice job

**Comment by Intensifiesx** [comment]
Additonally, when merging into main. I recommend using the updated collisions for base tiles. They are too bumpy as it is now.

Updated versions:
image
image
image
image

**Review by cozloff — COMMENTED** [review]
Great job implementing the borders on the edge tile borders. I apologize for my oversight on neglecting to create collisions on those bumpy tiles. They are not straight lines, and actually adjust to the curvature nicely.  I'm not well acclimated on how you can customize and add these borders, but please let me know if theres anything you need me to do for this.

**Comment by Intensifiesx** [comment]
Instead of tilemap collisions, it should be polygon colliders. Then after there is a corner editor to move corners. 
image

**Comment by fergut3** [comment]
Yeah that's probably the best way to add smooth borders. I tried experimenting by making tilemap colliders combining with the composite collider, but it still doesn't make it smooth.
Screenshot 2024-04-09 215053


 Regardless to make tiles we're gonna need to manually add the borders so it works. Ill see if there's ways to make it smoother in the future. Perhaps combining polygon colliders with the composite might do the trick but i'll fiddle with it.

**Pull request merged**
